ALTER TABLE users
  ADD COLUMN IF NOT EXISTS google_sub VARCHAR(255) NULL UNIQUE AFTER email,
  ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(30) NOT NULL DEFAULT 'local' AFTER google_sub,
  ADD COLUMN IF NOT EXISTS email_verified TINYINT(1) NOT NULL DEFAULT 0 AFTER auth_provider;
